#!/usr/bin/env bash

case $( uname -s ) in
    Linux)
        socat - UNIX-CLIENT:/home/liam/.run/clipper.sock
        ;;
    Darwin)
        echo "${@}" | pbcopy
        ;;
    *)
        echo "Unknown uname";
        exit 1;
    ;;
esac

