#!/usr/bin/env fish

# Ported (& modified) from bash by Liam Kearney.
# Original src: https://github.com/stuartsierra/dotfiles/blob/master/bin/fresh-chrome

# The MIT License (MIT)
#
# Copyright (c) 2013 Stuart Sierra
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# fresh-chrome
#
# Use this script on OS X to launch a new instance of Google Chrome
# with its own empty cache, cookies, and user configuration.
#
# The first time you run this script, it will launch a new Google
# Chrome instance with a permanent user-data directory, which you can
# customize below. Perform any initial setup you want to keep on every
# new Chrome instance, such as adding bookmarks and extensions. Then
# quit this Chrome instance with Command-Q or by selecting "Quit" from
# the "Chrome" menu. (The red "close" button is not sufficient.)
#
# AFTER that, every time you run this script it will launch a new
# Google Chrome instance with a temporary user-data directory copied
# from the one you set up the first time you ran this script. Every
# new instance of Google Chrome launched by this script will be
# completely isolated from the others.
#
# Note that Chrome on OS X will import the contents of
# ~/Library/Safari/History.plist when run for the first time.

# Permanent directory to store the user-data directories of your
# 'fresh' Chrome configurations.
set instances_dir "$HOME/.chromeinstances"

# Temporary directory in which to create new user-data directories for
# temporary Chrome instances.
set tmp_dir "/tmp"

function launch_chrome
    set -l user_data_dir "$argv[1]"
    exec open -na "Google Chrome" --args "--user-data-dir=$user_data_dir"
end

set default_dir "$instances_dir/_default"
set chrome_name "$argv[1]"

# Remove all instances but default.
if test $argv[1] = "clear"
    rm -rf $instances_dir/(ls $instances_dir | rg -v '^_default$')
    exit 0
end

if not test -d "$default_dir"
    echo "$default_dir"
    if test -z "$chrome_name"
        printf "Default Chrome user directory does not exist;\n"
        printf "have you run this script before?\n"
        printf "Run this script without arguments to create it,\n"
        printf "Then try again.\n"
        exit 1
    end
    mkdir -p "$default_dir"
    printf "Launching Chrome with default user dir $default_dir\n"
    printf "Customize this Chrome to set defaults for future uses\n"
    launch_chrome "$default_dir"
end

if test -z "$chrome_name"
    set user_dir "$default_dir"
else
    set user_dir "$instances_dir/$chrome_name"
end

if not test -d "$user_dir"
    cp -r "$default_dir" "$user_dir"
end

printf "Launching Google Chrome with user dir $user_dir\n"
launch_chrome "$user_dir"
