#!/usr/bin/env fish
#
# Kill notification center and restart it to dismiss notifications.

set domain "com.apple.notificationcenterui"

set bundlepath (lsappinfo info -only bundlepath $domain | cut -d '"' -f4)
set pid (lsappinfo info -only pid $domain | cut -d '=' -f2)

kill $pid > /dev/null 2>&1
open -n $bundlepath > /dev/null 2>&1
