#!/usr/bin/env bash

case $( uname -s ) in
    Linux)
        echo "${@}" | nc -U "$HOME/.run/opener.sock"
        ;;
    Darwin)
        /usr/bin/open "${@}"
        ;;
    *)
        echo "Unknown uname";
        exit 1;
    ;;
esac

