#!/usr/bin/env fish

set -l fish_trace on
docker-compose -f $HOME/DevRoute/docker-compose.yml up -d
docker-compose -f $HOME/Work/sproutlabs-pub/docker-compose.yml up -d
docker-compose -f $HOME/Work/glasshouse/docker-compose.override.yml -f $HOME/Work/glasshouse/docker-compose.yml up -d
docker-compose -f $HOME/Work/api-gateway/docker-compose.yml up -d
docker-compose -f $HOME/Work/moodle-local/docker-compose.yml up -d
docker-compose -f $HOME/Work/totara-local/docker-compose.yml up -d


