[[language]]
name = "rust"

[language.debugger]
command = "/Applications/Xcode.app/Contents/Developer/usr/bin/lldb-dap"
name = "Apple LLDB dap"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"

[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = false
